version: '3.7'

services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init_db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: 'car_rental'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5632:5432"

volumes:
  db-data: ~
